"""Initial Postgres Migration

Revision ID: 22103d4c8a24
Revises: 
Create Date: 2026-04-19 00:07:28.871593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22103d4c8a24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('name', name=op.f('uq_courses_name'))
    )
    op.create_table('generated_timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_timetables'))
    )
    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professors')),
    sa.UniqueConstraint('name', name=op.f('uq_professors_name'))
    )
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_code', sa.String(length=10), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slots'))
    )
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slots_slot_code'), ['slot_code'], unique=True)

    op.create_table('course_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('theory_slot', sa.String(length=10), nullable=True),
    sa.Column('lab_slot', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_offerings_course_id_courses')),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_course_offerings_professor_id_professors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_offerings'))
    )
    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_offerings_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_offerings_professor_id'), ['professor_id'], unique=False)

    op.create_table('course_professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_professors_course_id_courses')),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_course_professors_professor_id_professors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_professors'))
    )
    with op.batch_alter_table('course_professors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_professors_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_professors_professor_id'), ['professor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_professors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_professors_professor_id'))
        batch_op.drop_index(batch_op.f('ix_course_professors_course_id'))

    op.drop_table('course_professors')
    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_offerings_professor_id'))
        batch_op.drop_index(batch_op.f('ix_course_offerings_course_id'))

    op.drop_table('course_offerings')
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slots_slot_code'))

    op.drop_table('slots')
    op.drop_table('professors')
    op.drop_table('generated_timetables')
    op.drop_table('courses')
    # ### end Alembic commands ###
