"""Add indexes

Revision ID: 9a39c5ab7ab3
Revises: f09149fe41af
Create Date: 2026-04-18 22:47:47.308878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a39c5ab7ab3'
down_revision = 'f09149fe41af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_offerings_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_offerings_professor_id'), ['professor_id'], unique=False)

    with op.batch_alter_table('course_professors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_professors_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_professors_professor_id'), ['professor_id'], unique=False)

    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_slots_slot_code'), type_='unique')
        batch_op.create_index(batch_op.f('ix_slots_slot_code'), ['slot_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slots_slot_code'))
        batch_op.create_unique_constraint(batch_op.f('uq_slots_slot_code'), ['slot_code'])

    with op.batch_alter_table('course_professors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_professors_professor_id'))
        batch_op.drop_index(batch_op.f('ix_course_professors_course_id'))

    with op.batch_alter_table('course_offerings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_offerings_professor_id'))
        batch_op.drop_index(batch_op.f('ix_course_offerings_course_id'))

    # ### end Alembic commands ###
