"""add user auth

Revision ID: c216d6b921cb
Revises: 22103d4c8a24
Create Date: 2026-04-19 01:16:15.734981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c216d6b921cb'
down_revision = '22103d4c8a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_courses_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_courses_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_course_name_user', ['name', 'user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_courses_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('generated_timetables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_generated_timetables_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_generated_timetables_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_professors_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_professors_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_professor_name_user', ['name', 'user_id'])
        batch_op.create_foreign_key(batch_op.f('fk_professors_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_professors_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint('uq_professor_name_user', type_='unique')
        batch_op.drop_index(batch_op.f('ix_professors_user_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_professors_name'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('generated_timetables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_generated_timetables_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_generated_timetables_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint('uq_course_name_user', type_='unique')
        batch_op.drop_index(batch_op.f('ix_courses_user_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_courses_name'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('user_id')

    op.drop_table('users')
    # ### end Alembic commands ###
